# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - cd src
  - chmod +x ../bin/hugo
  - ../bin/hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  repo: chwergy/chwergy.github.io
  target_branch: master
  local_dir: src/public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
